services:
  bot:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
      # redis:  
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      
  # redis:
      # image: redis:latest
      # restart: always
      # ports:
      #   - "${REDIS_PORT}:${REDIS_PORT}"
      # volumes: 
      #   - redis-data:/data
      #   - redis-data:/usr/local/etc/redis/redis.conf
      # environment:
      #   REDIS_PASSWORD: ${REDIS_PASSWORD}
      #   REDIS_PORT: ${REDIS_PORT}
      #   REDIS_DATABASES: ${REDIS_DATABASES}

volumes:
  db-data:
  # redis-data:
  #   driver: local