version: '3.9'

services:

  db:

    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:${DB_PORT}"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080